ARG GO_VERSION={{.GoVersion}}
FROM golang:${GO_VERSION}-alpine AS build

ARG TARGETOS
ARG TARGETARCH

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY cmd ./cmd
COPY internal ./internal
{{- if .Pkg}}
COPY pkg ./pkg
{{- end}}

RUN --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH:-amd64} \
    go build -trimpath -ldflags "-s -w" -o /out/{{.ProjectName}} ./cmd/{{.ProjectName}}

FROM gcr.io/distroless/static-debian12:nonroot AS runtime

WORKDIR /
COPY --from=build /out/{{.ProjectName}} /{{.ProjectName}}

USER 65532:65532
ENTRYPOINT ["/{{.ProjectName}}"]
